### ISSUE TITLE
Error 500 al probar WebHook

### ISSUE THREAD

**Issue by armandocardenasf** [conekta/customer-magento-plugin#1]
Instale en Magento 2.3 el plugin de Conekta, pero el WebHook me esta regresando un error 500 siempre, aun desde la pagina de Pruebas de Conekta.

**Comment by magento-seis10** [comment]
Ya tengo la solución, si me aceptan como colaborador puedo enviar el PR

**Comment by marcoadasilvaa** [comment]
Mismo problema por aca con una instalacion limpia de magento 2.3.7 y sample data aparece el siguiente error al realizar el pago:

<br />
<b>Fatal error</b>:  Uncaught Error: Object of class Magento\Quote\Model\Quote\Item could not be converted to string in /var/www/html/vendor/conekta/conekta_payments/Gateway/Request/MetadataBuilder.php:133
Stack trace:
#0 /var/www/html/vendor/conekta/conekta_payments/Gateway/Request/MetadataBuilder.php(82): Conekta\Payments\Gateway\Request\MetadataBuilder-&gt;customFormat(Array, ' | ')
#1 /var/www/html/vendor/magento/module-payment/Gateway/Request/BuilderComposite.php(50): Conekta\Payments\Gateway\Request\MetadataBuilder-&gt;build(Array)
#2 /var/www/html/vendor/magento/module-payment/Gateway/Command/GatewayCommand.php(103): Magento\Payment\Gateway\Request\BuilderComposite-&gt;build(Array)
#3 /var/www/html/vendor/magento/module-payment/Model/Method/Adapter.php(547): Magento\Payment\Gateway\Command\GatewayCommand-&gt;execute(Array)
#4 /var/www/html/vendor/magento/module-payment/Model/Method/Adapter.php(462): Magento\Payment\Model\Method\Adapter-&gt;executeCommand('capture', Array)
#5 /var/www/html/vendor/magento/module-sales/Model/Order/Payment/O in <b>/var/www/html/vendor/conekta/conekta_payments/Gateway/Request/MetadataBuilder.php</b> on line <b>133</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/576011553724"}]}}
