### ISSUE TITLE
Not Working with Magento version 2.4

### ISSUE THREAD

**Issue by Abdulkadiragoliya** [conekta/customer-magento-plugin#15]
When Compile the code using di:compile its throwing error like 
In ClassReader.php line 51: 

Impossible to process constructor argument Parameter #3 [ <required> Conekta\Order $conektaOrder ] of Conekta\Payments\Gateway\Http\Client\CreditCard\TransactionCapture class

In ClassReader.php line 71:
Class Conekta\Order does not exist

**Comment by Reno-Axel** [comment]
Is not only un 2.4, 2.3 have the same problem, because Conekta\Order class was remove from lib folder

**Comment by fcarrero** [comment]
we've updated this repo in order to support those versions, feel free to try it again
