### ISSUE TITLE
Unable to pay due to leftover \Conekta\Conekta references

### ISSUE THREAD

**Issue by MagicLegend** [conekta/customer-magento-plugin#44]
Hi,

I'm updating the extension from v4.1.9 to v5.0.4, and I noticed that it breaks checkout with either payment methods (although for us only Oxxo/cash is important). When trying to place an order, PHP will throw the `ERROR: Class "Conekta\Conekta" not found` exception. This is because the updated `conekta/conekta-php` module no longer has the referenced `\Conekta\Conekta` class. [You removed some of the references to that class from this extension](https://github.com/conekta/customer-magento-plugin/compare/4.1.9...5.0.4#diff-9d8f8bb39dfd46426a24d8fd10c888e246a3a501d2684a7a3af5da46b8c8af58L4) ([and left some as commented code](https://github.com/conekta/customer-magento-plugin/compare/4.1.9...5.0.4#diff-03505c2e73f04a85131904e82222a99dcd1f5b30ec35e1f07da47460821ebeaaR107-R108)), but I suspect these were forgotten:

https://github.com/conekta/customer-magento-plugin/blob/4adcee5f94d36d963aa9fff94595b04b63f835a0/Gateway/Http/Util/HttpUtil.php#L29-L33

Given that this function is still called in constructors of both payment methods, it means it'll always crash:

https://github.com/conekta/customer-magento-plugin/blob/4adcee5f94d36d963aa9fff94595b04b63f835a0/Gateway/Http/Client/Cash/TransactionAuthorize.php#L77
https://github.com/conekta/customer-magento-plugin/blob/4adcee5f94d36d963aa9fff94595b04b63f835a0/Gateway/Http/Client/BankTransfer/TransactionAuthorize.php#L74

For us, the call stack when placing an order via GraphQL is as follows:
![image](https://github.com/conekta/customer-magento-plugin/assets/3169104/4cd9f803-0e5b-4ecd-938b-3d5e876ec442)

I don't think any of our customizations have impact on this flow, but please correct me if I'm wrong.

Thanks.

**Comment by fcarrero** [comment]
working on it

**Comment by MagicLegend** [comment]
Hi @fcarrero,

I can confirm that this fixes the issue. Can this please be released as the next version? Currently `5.0.5-beta1` is not visible in composer for me (but the branch is, which I used to test with):

![image](https://github.com/conekta/customer-magento-plugin/assets/3169104/d6467075-d5f8-4c94-b558-db683d584bdb)

Thanks.
